hhvm/hhvm-third-party

CMakeLists.txt

If we already have appropriate versions of:
* fastlz
* libsqlite3
* lz4
* double-conversion
then we don't need to build them.
This change also lessens the required patches for distro
inclusion in both Debian and Fedora
I'm not really sure if the logic is correct in the
double-conversion header installation. Please check it.

Stop building libs that already exist on the system

---

CMakeLists.txt

If we already have these two on the system, there is no need to
build them.

Do not build libafdt and libmbfl if we have it

---

mcrouter/CMakeLists.txt

Now the library requirement is 1.48,but the compile hhvm will can't find the context library,because the context library in 1.51.0 above.
Summary:
http://www.boost.org/users/history/version_1_51_0.html

context lib need to boost library 1.51.0 above

---

mcrouter/config-impl.h

Detected by clang 3.6:
'incl_THIRD_PARTY_MCROUTER_CONFIG_IMPL_H' is used as a header guard here,
followed by #define of a different macro [-Wheader-guard]

Fix typo in mcrouter header guard.

---

folly/CMakeLists.txt

The Boost 'context' library is now required to compile folly in
the version checked out here. The context library is required in the
file folly/experimental/fibers/BoostContextCompatibility.h.

Add boost 'context' library to Folly CMake list

---

folly/CMakeLists.txt
thrift/CMakeLists.txt

Because, without some massive pains, the symlinks don't translate nicely on windows.
This doesn't remove the actual symlinks yet.

Remove folly and thrift's dependence on symlinks

---

libzip/mkstemp.c

This was removed at some point, but it is needed for Windows. The CMake file already references it.

Add mkstemp.c back to libzip

---

webscalesqlclient/CMakeLists.txt

The space in the middle of the line meant that the originally passed in CMAKE_C_FLAGS did not get associated with the CMAKE_C_FLAGS= to the left. The end result was that no passed in flags were retained. You would only get -Wno-maybe-uninitialized. By doing the concatenation as a separate step, the right thing happens.

Fixed passing of CMAKE_C_FLAGS.

---

libzip/zipint.h

We build libzip as a static library, so the functions shouldn't be getting exported from the final binary.

Don't export function in libzip

---

thrift/CMakeLists.txt

Firstly, because I didn't want to deal with building them as a static library on MSVC.
And also because don't use them, and we also don't link against the kerberos libraries, so even if we did use them, it would error at link time.

Don't build the kerberos utils in thrift

---

CMakeLists.txt

Because this would be a nightmare to port, and is only needed for the takeover agent, which I'll disable under MSVC in a future PR.
This also disables the ability to set a custom path for libafdt, for the reasons outlined in #78.

Don't build libafdt under MSVC.

---

.gitmodules
webscalesqlclient/CMakeLists.txt
webscalesqlclient/src

Summary:
This attempt simply redirects the src/, I deleted the webscalesql-5.6 folder (which won't really deleted if the submodule is init'd), I updated the CMakeFile to point to src so maybe next time we need to change a repo it won't be so hard.
Test Plan:
When this patch is applied we get this output:
From https://github.com/drilibo/hhvm-third-party
* branch            addmysql56 -> FETCH_HEAD
Updating 695d044..9f6ae51
warning: unable to rmdir webscalesqlclient/webscalesql-5.6: Directory not empty
Fast-forward
.gitmodules                       | 7 +++----
webscalesqlclient/CMakeLists.txt  | 2 +-
webscalesqlclient/mysql-5.6       | 1 +
webscalesqlclient/src             | 2 +-
webscalesqlclient/webscalesql-5.6 | 1 -
5 files changed, 6 insertions(+), 7 deletions(-)
create mode 160000 …

Change webscalesql submodule

---

mcrouter/CMakeLists.txt

This causes issues for some as `file(COPY)` doesn't work on symlinks, and doing that under windows is just a pain.
This just writes a file which directly includes the target of the symlink instead.
This should fix [HHVM #6532](https://github.com/facebook/hhvm/issues/6532).

Don't use symlinks for some of the MCRouter headers

---

libmbfl/mbfl/CMakeLists.txt
libmbfl/mbfl/mbfl_defs.h

We build libmbfl as a static library, but the headers don't currently realize that, and declare everything with dllexport or dllimport, as if we'd built a dynamic library.
This adds a small adjustment in a header, and adds a definition to ensure it's used when we build mbfl.

Allow building libmbfl as static under windows

---

proxygen/CMakeLists.txt

Because MSVC doesn't understad `-Wno-unused-variable`, and gives errors.

Don't pass -Wno-unused-variable to build proxygen for MSVC

---

CMakeLists.txt

The core of HHVM unconditionally links directly against the mbfl target, so we can't allow it to be excluded from building.
Technically, the afdt is the same way, but as doing that change here will conflict with the next PR I'm about to open, I've not touched it as part of this PR.

Don't allow a custom path for LIBMBFL_LIBRARY

---

proxygen/CMakeLists.txt

We can't pass environment variables before the bash script when on Windows, so pass them as arguments instead.
This also allows setting a custom path for gperf, because requiring gperf to be in your path on Windows is a bit excessive.
This depends on [proxygen#55](https://github.com/facebook/proxygen/pull/55) being merged upstream first.
This also depends on [#82](https://github.com/hhvm/hhvm-third-party/pull/82), and will conflict with it as well, due to the proximity of the changes.

Generate the proxygen headers in a windows friendly way

---

proxygen/CMakeLists.txt

Because they don't work on windows.
This also adds the appropriate `DEPENDS` statements to the pair of custom commands, as they would conflict with my next PR if they were in a separate PR.

Eliminate Proxygen's dependence on symlinks

---

libmbfl/mbfl/CMakeLists.txt
libmbfl/mbfl/mk_eaw_tbl.awk

The first thing this does is remove the explicit call to `sh`, because all that does is break things on Windows.
The second thing we do is inline the definition of strtonum from awk (which is public domain), to allow running the script under the version of awk provided by msysgit.

Allow building libmbfl on Windows

---

folly/gen/GroupVarintTables.cpp

From `folly/gen` subfolder, run:
```
python ../src/folly/build/generate_varint_tables.py
```
Reason: PPC64 platform needs it in order to compile hhvm. db3d4d356e0fdabb2f80046bd77f05207d530bba missed it.

Update folly/gen/GroupVarintTables.cpp according to new code generator

---

ragel/CMakeLists.txt

Adds compatibility for CMake < 2.8.12 which does not natively support "add_compile_options", such as CMake 2.8.11 bundled in CentOS 7.

FIX: add compatibilty for CMake < 2.8.12

---

mcrouter/CMakeLists.txt

When building in a separate build directory, ragel errors out because
the parent directories for the generated files don't exist.

Create parent directory for generated files in mcrouter

---

mcrouter/CMakeLists.txt

mcrouter no longer uses CaretReplyConverter.h. I've removed its creation from the cmake files so that git status does not report the file as a new untracked file.

Removed unused CaretReplyConverter.h.

---

libafdt/CMakeLists.txt

This way it gets caught by the `.gitignore` properly.
Also make it possible to build it as a shared library.
Closes #49

Put the libafdt config header in the path it's expected to be generated in

---

webscalesqlclient/CMakeLists.txt

Let HPHPCompiler deal with it for us. The `maybe-unused` warning also doesn't exist on clang 3.6, so was spamming the build output.
Depends on internal diff D4663382.

Don't explicitly disable the maybe-unused warning for webscalemysql

---

CMakeLists.txt

This fixes the case where we find an lz4 library installed, but it is not a supported version.  See https://github.com/facebook/hhvm/issues/7804

LZ4_LIBRARY -> LZ4_FOUND

---

folly/CMakeLists.txt

An earlier commit introduced a problem for Aarch64 builds 
since it added an  X86_64 specific compiler option.  See,
formt:612536a Apply -mpclmul to the one file that needs it.
This commit predicates that change.

predicate X86_64 option in folly third-party build

---

folly/CMakeLists.txt

This has been breaking the debian7 builds for the last couple releases.  See:
https://github.com/facebook/hhvm/commit/93b716be21cf380f786ab2f86b35c13a07c5caf0
I have to rebuild 3.22 to include this because we forgot to add this back into master.  Apparently we didn't update folly between the two releases.

Add remove for broken example.

---

ocaml/CMakeLists.txt
third_party_notices.txt

This is in the "I don't understand how this ever worked" bucket:
- cmake does not support single-quoted arguments
- multi-line strings need escapes
... so.... *shrug*
Test Plan: I was able to reliably reproduce the failures locally now.
With this change, I can't.

Hopefully make automatic builds more reliable

---

ocaml/CMakeLists.txt

opam2 still needs ocaml binaries to be built (next PR will remove
this). So we still need to make the 'opam' target depend on 'ocamlc'
Without this fix, aggressive parallel build might fail when trying to compile opam while ocaml is not build yet.
Sorry about that :D

Fix opam2 build dependecies

---

rsocket-cpp/CMakeLists.txt
thrift/CMakeLists.txt

Needs an HHVM diff to CMake too.
Always build rsocket-cpp/yarpl - a reactive programming library - as
Thrift always depends on it, even if not being built with full rsocket
support.

Don't build rsocket + thrift rsocket support if OpenSSL is too old
